# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nfilipe- <nfilipe-@student.42lisboa.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/15 19:53:58 by nfilipe-          #+#    #+#              #
#    Updated: 2022/11/15 19:58:19 by nfilipe-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SHELL = /bin/sh 
# avoids trouble with any 'SHELL'-named variable

.SUFIXES:					   
.SUFIXES:	.a .c .h .o
# deletes the default suffixes
# defines our suffix list

SRCS	=	

BONUS	=	

SRCS.O	=	

BONUS.O	=	

NAME	=	libftprintf.a

CC		=	cc 
CFLAGS	=	-O2 -Wall -Wextra -Werror -I.

all:		$(NAME) ;






info:	
		@echo Makefile for \'libftprintf.a\' v0.1.15112022 by nfilipe-

.PHONY:	all bonus clean fclean re info
# A phony target is one that is not really the name of a file; rather it \
is just a name for a recipe to be executed when you make an explicit \
request.It mainly avoids a conflict with a file of the same name

.SILENT:	
# 'make' will not print the recipe used to remake those particular files \
before executing them.